import type { Book } from './types';

export const mockBooks: Book[] = [
  {
    id: '1',
    title: 'Le Mythe de Sisyphe',
    author: 'Albert Camus',
    coverUrl: 'https://placehold.co/400x600.png',
    pdfUrl: '/mock-book.pdf',
    aiHint: 'philosophy book',
  },
  {
    id: '2',
    title: 'Vingt mille lieues sous les mers',
    author: 'Jules Verne',
    coverUrl: 'https://placehold.co/400x600.png',
    pdfUrl: '/mock-book.pdf',
    aiHint: 'adventure novel',
  },
  {
    id: '3',
    title: 'L\'Étranger',
    author: 'Albert Camus',
    coverUrl: 'https://placehold.co/400x600.png',
    pdfUrl: '/mock-book.pdf',
    aiHint: 'classic literature',
  },
  {
    id: '4',
    title: 'Le Rouge et le Noir',
    author: 'Stendhal',
    coverUrl: 'https://placehold.co/400x600.png',
    pdfUrl: '/mock-book.pdf',
    aiHint: 'historical novel',
  },
  {
    id: '5',
    title: 'Voyage au bout de la nuit',
    author: 'Louis-Ferdinand Céline',
    coverUrl: 'https://placehold.co/400x600.png',
    pdfUrl: '/mock-book.pdf',
    aiHint: 'modernist novel',
  },
  {
    id: '6',
    title: 'La Gloire de mon père',
    author: 'Marcel Pagnol',
    coverUrl: 'https://placehold.co/400x600.png',
    pdfUrl: '/mock-book.pdf',
    aiHint: 'autobiography childhood',
  },
  {
    id: '7',
    title: 'Dune',
    author: 'Frank Herbert',
    coverUrl: 'https://placehold.co/400x600.png',
    pdfUrl: '/mock-book.pdf',
    aiHint: 'science fiction',
  },
  {
    id: '8',
    title: '1984',
    author: 'George Orwell',
    coverUrl: 'https://placehold.co/400x600.png',
    pdfUrl: '/mock-book.pdf',
    aiHint: 'dystopian novel',
  },
  {
    id: '9',
    title: 'Le Petit Prince',
    author: 'Antoine de Saint-Exupéry',
    coverUrl: 'https://placehold.co/400x600.png',
    pdfUrl: '/mock-book.pdf',
    aiHint: 'childrens book',
  },
  {
    id: '10',
    title: 'Fahrenheit 451',
    author: 'Ray Bradbury',
    coverUrl: 'https://placehold.co/400x600.png',
    pdfUrl: '/mock-book.pdf',
    aiHint: 'speculative fiction',
  },
  {
    id: '11',
    title: 'Les Misérables',
    author: 'Victor Hugo',
    coverUrl: 'https://placehold.co/400x600.png',
    pdfUrl: '/mock-book.pdf',
    aiHint: 'french literature',
  },
  {
    id: '12',
    title: 'Le Parfum',
    author: 'Patrick Süskind',
    coverUrl: 'https://placehold.co/400x600.png',
    pdfUrl: '/mock-book.pdf',
    aiHint: 'thriller novel',
  },
];
